# Generated by Django 3.2.8 on 2023-02-23 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.CharField(max_length=200)),
                ('Latex', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EquationImageModel',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ImageRaw', models.ImageField(upload_to='images')),
                ('ImageRefined', models.ImageField(default=None, null=True, upload_to='images')),
                ('Equation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equation')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('IdCode', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=500)),
                ('Votes', models.IntegerField()),
                ('Equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equation')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images')),
                ('CharacterSet', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=1)),
                ('EncodedLabel', models.IntegerField()),
                ('Verified', models.BooleanField(default=False)),
                ('EquationImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equationimagemodel')),
            ],
        ),
    ]
