# Generated by Django 3.2.8 on 2023-02-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='Image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equationimagemodel',
            name='ImageRaw',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equationimagemodel',
            name='ImageRefined',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
