# Generated by Django 3.2.8 on 2023-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230223_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationimagemodel',
            name='Id',
            field=models.CharField(default='ddfc0947-7eb4-4404-a26a-e6f2b42f2612', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
