# Generated by Django 3.2.8 on 2023-02-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equationimagemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationimagemodel',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
