# Generated by Django 3.2.8 on 2023-02-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equationimagemodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equationimagemodel',
            name='Equation',
        ),
        migrations.DeleteModel(
            name='CharacterImage',
        ),
        migrations.DeleteModel(
            name='EquationImageModel',
        ),
    ]
