# Generated by Django 3.2.8 on 2023-02-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230224_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquationImageModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageRaw', models.CharField(max_length=200)),
                ('ImageRefined', models.CharField(default=None, max_length=200, null=True)),
                ('Equation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equation')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=200)),
                ('CharacterSet', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=1)),
                ('EncodedLabel', models.IntegerField()),
                ('Verified', models.BooleanField(default=False)),
                ('EquationImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equationimagemodel')),
            ],
        ),
    ]
